server:
  servlet:
    # Servlet 上下文路径，默认/,可以通过此方式设置上下文访问路径
    context-path: /maque-sys
  port: 8080

spring:
  datasource:
    name: maque-sys
    # 数据源类型，使用DruidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库连接 url
    url: jdbc:mysql://localhost:3306/maque-sys
    # 驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 用户名
    username: root
    # 密码
    password: 111111
    # 开启监控统计
    filters: stat
    # 初始连接数
    initial-size: 2
    # 最大空闲连接数
    max-idle: 10
    # 最小空闲连接数
    min-idle: 1
    # 最大活动数
    max-active: 20
    # 获取连接等待时间
    max-wait: 60000
    # 间隔个多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    # 一个连接在池中最小生存的空间
    min-evictable-idle-time-millis: 300000
    # 验证连接是否有效的SQL,不同的数据配置不同
    validation-query: SELECT 'x'
    # 指明连接是否被空闲连接回收器（如果有）进行检测，如果检测失败,则连接将被从池中移除
    test-while-idle: true
    # 借出连接是不要测试，否则影响性能
    test-on-borrow: false
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp